language: python

python:
    - "3.5"
    - "3.6"
    - "3.7-dev"

before_install:
    - pip install --upgrade pip
    - pip install poetry

install:
    - poetry install

script:
    - poetry run flake8
    - poetry run py.test tests/
