language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install .

script:
    - flake8
    - py.test tests/
